/*
* This file was auto-generated by zoa_export.py
* DO NOT EDIT MANUALLY
*/
#include "civ/civ.h"

typedef struct {
}  Empty;

void  Empty_txZoab(Ring* r, Empty* t) {
}

typedef struct {
  U4 a;
}  One;

void  One_txZoab(Ring* r, One* t) {
  U4_txZoab(r, t->a);
}
